{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
      protocol: TCP
{{- end }}
