image:
  repository: ghcr.io/OWNER/k8s-ms
  tag: latest
  pullPolicy: IfNotPresent

frontend:
  enabled: true
  image: ""
  replicas: 2
  service:
    type: ClusterIP
    port: 3000
  env:
    BACKEND_URL: "http://backend:5000"

backend:
  enabled: true
  image: ""
  replicas: 2
  service:
    type: ClusterIP
    port: 5000

redis:
  enabled: true
  image: "redis:7.0-alpine"
  replicas: 1
  service:
    type: ClusterIP
    port: 6379

ingress:
  enabled: false
  host: chart-example.local
  annotations: {}
